SELECT 
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN N ELSE 0 END AS this_week_N,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN P ELSE 0 END AS this_week_P,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN K ELSE 0 END AS this_week_K,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN N ELSE 0 END AS prev_week_N,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN P ELSE 0 END AS prev_week_P,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN K ELSE 0 END AS prev_week_K
FROM lora_npk_t
WHERE WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now()) LIMIT 10;