SELECT 
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN N ELSE 0 END AS this_week_N,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN P ELSE 0 END AS this_week_P,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-1 AND WEEK(now()) THEN K ELSE 0 END AS this_week_K,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN N ELSE 0 END AS prev_week_N,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN P ELSE 0 END AS prev_week_P,
    CASE WHEN WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now())-1 THEN K ELSE 0 END AS prev_week_K
FROM lora_npk_t
WHERE WEEK(FROM_UNIXTIME(time)) BETWEEN WEEK(now())-2 AND WEEK(now()) LIMIT 10;

SELECT 
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 1 THEN SMoist END AS Sunday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 2 THEN SMoist END AS Monday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 3 THEN SMoist END AS Tuesday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 4 THEN SMoist END AS Wednesday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 5 THEN SMoist END AS Thursday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 6 THEN SMoist END AS Friday,
  CASE WHEN DAYOFWEEK(FROM_UNIXTIME(time)) = 7 THEN SMoist END AS Saturday
FROM soil_moist_t
WHERE FROM_UNIXTIME(time) >= DATE_SUB(CURRENT_DATE, INTERVAL 7 DAY)
ORDER BY FROM_UNIXTIME(time) ASC;